resource "aws_lambda_function" "create_page_view" {
  function_name = "create_page_view"
  handler       = "create_page_view.lambda_handler"
  runtime       = "python3.12"
  role          = aws_iam_role.lambda_exec_role.arn

  # This will point to the zip file generated by GitHub Actions and checked out in the repo
  filename         = "lambdas/create_page_view.zip"  
  source_code_hash = filebase64sha256("lambdas/create_page_view.zip")
}
